### ISSUE TITLE
Export fehlerhaft, wenn "storage" unvollständig ausgefüllt wurde

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#1]
**Ergebnis fehlerhafter Export:**

![screenshot_2018-07-02 hermine](https://user-images.githubusercontent.com/37943763/42149578-1a734156-7dd7-11e8-9b49-8b7fd49ce514.png)

**Reproduktion:**
In einem Projekt ein Storage anlegen und ein beliebiges Storage-Feld frei lassen. Projekt Exportieren, dann importieren. 

**Lösungsvorschlag:**
a) leere Felder werden fehlerfrei exportiert
b) Pflichtfelder
c) ?

**Comment by Patrick-Werner-WEBTH** [comment]
Wird ein neuer Storage erstellt sind die auszufüllenden Felder nun nichtmehr mit Placeholder 99 vorbelegt, sonder mit Value 0 (null).
Auch werden leere Felder nun als 0 (null) gespeichert und danach dementsprechend angezeigt.
