### ISSUE TITLE
Standardbenutzer kann Rechte eskalieren

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#10]
**Problem:**
Ein neu angelegter Benutzer kann nach erfolgten Login die komplette Userliste abrufen und danach Konten löschen.

**Reproduktion:**
Einen beliebigen Nutzer erstellen. Mit dem neuen Benutzer einloggen. Dann kann man sich über `https://hermine.local/ajax/auth/getFullUserList` alle angelegten Benutzer ausgeben lassen.
In der Konsole der Entwicklertools von Firefox oder Chrome kann man mit dem Wissen über die NutzerIDs oder durch Probieren mit `$.post(https://hermine.local/ajax/auth/removeUser",{id:1});` beliebige Nutzerkonten löschen.

**Lösungsvorschlag:**
Dieser Bug sollte bei der Bearbeitung von #9 mit behoben werden.

**Comment by Patrick-Werner-WEBTH** [comment]
Funktionen angepasst sodass "Worker" keine Daten mehr abfragen können und diese auch nicht verändern/löschen können.
