### ISSUE TITLE
Projektarchiv als browsbarer iframe

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#12]
**Problem:**
Die attachments für das Projekt können schnell unübersichtlich werden, da keine Ordnerstruktur vorhanden ist.

**Lösungsvorschlag:**
- wie am 05.07.2018 besprochen soll die Uploadfunktion durch einen iFrame o.Ä. ersetzt werden. Dort soll die Verzeichnisstruktur eines im /archive/$Projektname von hermine liegenden Ordners über das directory-listing `Options +Indexes` bzw `Options FancyIndexing` durch eine .htaccess angezeigt werden.
- Der iFrame sollte sich auf eine praktikable Höhe beschränken, aber die Verzeichnisse und Dateien vollständig auflisten. --> Scrollbar (Das Ansehen von Dateien zur Zuordnung wird nur selten von kleineren Mobilgeräten aus geschehen. Das wird eher nach der Bergung der Trümmer an einer Zwischenstation mit Laptop oder Festrechner geschehen.)
- Der Upload in dieses Verzeichnis erfolgt durch die Administratoren durch physischen zugriff auf den Server oder über einen speziellen SFTP/SSH-Account, der individuell erstellt werden muss.
- Frage: ist es möglich/praktikabel diesen Ordner in den import/export (vielleicht sogar als optionale Auswahl) mit aufzunehmen?

**Comment by Patrick-Werner-WEBTH** [comment]
@kaymueller 
Der FileUpload wurde entfernt und durch den iFrame erstzt.
Über ein Input-Feld kann der Pfad zum Ordner gepflegt werden.
Der Ordner "archiv" wurde mit einem "Test" Ordner angelegt. Über die .htaccess im "Projekt-Ordner" kann über die "IndexOptions FancyIndexing" Optionen das Verhalten angepasst werden hierzu ein Link:
http://michael-puff.de/Programmierung/Artikel/FancyIndexing.shtml

Durch den iFrame ist es Möglich das der zugegriffen Ordner "überall" liegen kann, sofern die nötigten Berechtigungen vorhanden sind.
