### ISSUE TITLE
Eingabe des Lagerplatzes

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#2]
**Problem:**
Unter "projects" als auch im erstellten "item" können sowohl Zahlen als auch Buchstaben als Lagerplatz eingegeben werden. Außerdem sind diese unabhängig vom vorgegebenen Wert wählbar. Das könnte zu fehlerhaften, nicht möglichen Lagerplätzen führen.

![screenshot_2018-07-02 hermine 1](https://user-images.githubusercontent.com/37943763/42150142-18380078-7dd9-11e8-8259-9be12597ec43.png)

![screenshot_2018-07-02 hermine 2](https://user-images.githubusercontent.com/37943763/42150616-b0bb964c-7dda-11e8-9554-5d5eb85e4a50.png)

**Lösungsvorschlag:**
In den Projekteinstellungen:
Wie bei "GridY" sollten nur Zahlen zulässig sein. Als Indikator sollte man ebenfalls "99" als Placeholder einsetzen.
Auf der Itemseite:
Bei der Eingabe am item sollte man die 4 Felder wie beim darüberliegenden "Grid" gestalten. Sodass man in einem oberen weißen Freitextfeld eine Zahl eingibt und diese in einem Dropdown bestätigt, wonach sie in einem grauen Feld darunter angezeigt wird.

**Comment by Patrick-Werner-WEBTH** [comment]
Auf Project Ebene können nur noch Zahlen eingegeben werden.

**Comment by Patrick-Werner-WEBTH** [comment]
Item Seite:
Storage eingaben erfolgen nun wie bei Grid über das Dropdown.
