### ISSUE TITLE
Attachments Download landet in Ladeschleife

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#3]
**Problem:**
Beim Versuch einen hochgeladenen Anhang im Projekt oder im Item herunterzuladen, gerät man in eine Weiterleitungsschleife.

**Reproduktion:**
Beliebige Datei hochladen und über den blauen Downloadknopf versuchen herunterzuladen.

**Comment by Patrick-Werner-WEBTH** [comment]
@kaymueller 
Hier müssen wir vlt einmal per TeamViewer gucken wie das bei dir aussieht, konnte diesen Zusand mit keiner Einstellung Reproduzieren.
