### ISSUE TITLE
Lagerplatzänderung im Changelog hinterlegen

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#4]
**Problem:**
Derzeit wird nur das erste anlegen eines Lagerortes im Changelog hinterlegt.

**Lösungsvorschlag:**
Die Modifikation eines Lagerortes wird ebenfalls im Changelog hinterlegt.

**Comment by Patrick-Werner-WEBTH** [comment]
Abfrage angepasst, es wurde nur auf Änderung des Lagerplatzes geprüft nicht auf Verschiebung innerhalb eines Lagerortes.
Nun wird jede Änderung "aufgezeichnet".
