### ISSUE TITLE
Leere Auswahlfelder für Storage und Structure

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#5]
**Problem:**
Wenn man ein item fälschlicherweise einer "structure" oder "Storage" zugeordnet hat, ist es derzeit nicht möglich diese Auswahl zu wiederrufen. 

**Lösungsvorschlag:**
In den Dropdowns von Structure" und "Storage" ein leeres Auswahlfeld hinzufügen.

**Comment by kaymueller** [comment]
**Nach Rücksprache vom 05.07.2018:**
- Structures: Es soll vom Projektmanager eine Structure "Nicht zugeordnet" respektive "not assigned" erstellt werden, die dann ausgewählt werden kann. 
- Storage: Nachdem wir gestern die Option einer Checkbox besprochen haben, würde ich persönlich ein leeres Auswahlfeld oder eines das sagt "not stored", bei dessen Auswahl die Eingabefelder geleert und deaktiviert werden bevorzugen. Passt einfach besser zum Workflow als eine Checkbox. Sollte es aus Versehen angewählt werden, kann man ja einfach ins changelog schauen ( siehe #4 ) und den Lagerplatz wieder eintragen.

**Comment by Patrick-Werner-WEBTH** [comment]
Storage:
Es gibt nun immer die Option "not stored"
Wird diese ausgewählt kann im Eingabefeld nur noch 0(null) eingegeben werden, optional können die Werte auch nicht angepasst werden, das System speichert diese dann trotzdem als 0 (null) ab sofern "not stored" ausgewählt ist.
