### ISSUE TITLE
Itembild bleibt nach Löschung des Items erhalten.

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#6]
**Problem:**
Wenn ein Bild einem Item zugeordnet wurde, bleibt diese Zuordnung auch erhalten, nachdem das Item gelöscht wurde und ein neues Item unterselben Namen angelegt wird.

**Reproduktion:**
Item mit beliebigen Namen anlegen, Bild hinzufügen, Item löschen, Item mit selben Namen erneut anlegen.

**Lösungsvorschlag:**
Das Bild muss beim Löschen des Items ebenfalls gelöscht werden.

**Comment by Patrick-Werner-WEBTH** [comment]
Nach dem löschen war auch noch der Ordner des Items vorhanden.

Beim löschen eines Items, wird nun das Bild gelöscht und der Ordner des Items (somit auch /images/ und /files/).
