### ISSUE TITLE
Doppelte Items nach Import von gleichnamigen Projekten

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#7]
**Problem:**
1) Wird ein Projekt mit identischen Titel eines bestehenden Projekts importiert, werden die Items in beiden Projekten dupliziert. Die doppelten Items bleiben auch nach Löschen des gleichnamigen importieren Projekts erhalten.
2) Wird ein Projekt unvollständig ausgefüllt exportiert, kann es nicht fehlerfrei importiert werden. Könnte mit  #1 zusammenhängen.

**Reproduktion:**
1) Projekt mit $Name und midnestens einem $Item exportieren. Projekt importieren.
2) Projekt mit $Name und mindestens einem $Item anlegen, exportieren, dann löschen. Projekt importieren. 

**Lösungsvorschläge:**
1) Exportierte Projekte mit Zeitstempel versehen: $Name_YYMMDD_HHMMSS
2) ?

**Comment by Alexander-Kunz-WEBTH** [comment]
**Problem 1**
Jetzt habe ich mir das in Ruhe angeschaut und verstanden. Zur Erklärung: Jedes Projekt bekommt als Referenzschlüssel, u.a. für die dazugehörigen Items, eine globale, eindeutige, ID wie z.B. testprojekt27a791cb7-f0b3-a92a-f22c-7e8fa3d10edc
Die Wahrscheinlichkeit für zwei identische Referenzschlüssel, selbst bei gleichem Projektnamen, ist in Anbetracht der geplanten Nutzung nahe null.
Ausgehebelt wird das Ganze natürlich, wenn du in derselben Instanz die Projekte exportierst und daraufhin in derselben Instanz wieder importierst. Nebeneffekt ist, dass dann auch die Items doppelt angelegt und dargestellt werden.
Aus diesem Grund wird nun beim Import überprüft, ob bereits ein Projekt mit demselben Schlüssel existiert. Falls ja, wird der Import abgebrochen und eine entsprechende Fehlermeldung dargestellt.
Darüber hinaus habe ich dem Import-Prozess weitere Fehlermeldungen hinzugefügt.

@WEBTH-Patrick-Werner Änderungen sind im SVN, bitte auf Git stellen und **Problem 2** noch lösen.

**Comment by Patrick-Werner-WEBTH** [comment]
@kaymueller 
Bitte einmal mit der neusten Version ausprobieren, bei mir hatte es keinen Fehler mehr.
