### ISSUE TITLE
Loginabfrage verrät falschen Parameter

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#8]
**Problem:**
Versucht man sich mit falschen Logindaten anzumelden, kann man in der Antwort der errorMessage sehen, welchen Teil man falsch eingegeben hat. Das macht es potenziellen Angreifern leichter Logindaten zu erraten. Die Umsetzung in der UI ist richtig.

- falscher Benutzername:
![grafik](https://user-images.githubusercontent.com/37943763/42260937-a19a21dc-7f66-11e8-903f-885771e779e3.png)

- falsches Passwort:
![grafik](https://user-images.githubusercontent.com/37943763/42260804-1e571ae6-7f66-11e8-92bb-e150a4ebb6ae.png)

**Lösungsvorschlag:**
Die Errorcodes/Errormessages auf "Invalid credentials" vereinheitlichen.

**Comment by Patrick-Werner-WEBTH** [comment]
Errorcodes/Errormessages auf "Invalid credentials" vereinheitlicht.
