### ISSUE TITLE
Benutzerrollen

### ISSUE THREAD

**Issue by kaymueller** [JaegerIngenieure/hermine#9]
**Problem:**
- Die derzeitigen Nutzerrollen sind nicht eindeutig abgegrenzt. 
- Beim Erstellen eines neuen Nutzers ist diesem die Rolle "none" zugewiesen. 
- Die Permissionskategorie heißt Settings, obwohl der Menüpunkt User heißt
- Es existiert zudem noch die Rolle "Framework Administrator" dessen Nutzen nicht ersichtlich ist. 
- Welche Funktion erfüllt die "Administrator" Checkbox beim Erstellen von neuen Benutzern? Wird die Benutzerrolle nicht über die Dropdowns in den Benutzereinstellungen gesteuert?

**Lösungsvorschlag:**

- Die drei Kategorien-Methode (User,Items,Projects) sollte definitiv erhalten bleiben
- Neu angelegte Benutzer bekommen die niedrigste Rechtestufe "Worker" in den drei Kategorien zugewiesen.
- Permissionrolle "Settings" zu "User" umbenennen
- Drei Nutzerrollen:
-- Administrator
-- Supervisor
-- Worker

- _Die Zugriffsrechte sollten wie folgt vergeben werden:_
1) **Administrator**
User: Vollzugriff
Items: Vollzugriff
Projects: Vollzugriff
2) **Supervisor**
User: Rechtevergabe ist auf Worker und Supervisor beschränkt (kann keine Administratorkonten erstellen / kann keine Administratorrechte vergeben), kann nur Worker oder Superviser löschen / bearbeiten
Items: Vollzugriff
Projects: kann Projekte nicht löschen, kein Import von Projekten
3) **Worker**
User: kann nur seinen Namen und sein Passwort ändern
Items: Vollzugriff
Projects: kann nur die Lagerbelegung und die Item-Evaluation ansehen

**Comment by kaymueller** [comment]
**Nach Rücksprache vom 05.07.2018:**
- Die Benutzerrolle "Framework-Administrator" bleibt für internes debugging erhalten.
- es soll dokumenteiert werden, welche Zusatzrechte/Einschränkungen die jeweilige Rolle mit sich bringt
- Die "Administrator?"-Checkbox soll entweder eine bessere Bezeichnung erhalten, da sie nur die "Permissions" und "Default Project" Optionen in den Usersettings freischaltet. Theoretisch kann man die Checkbox auch weglassen und das ganze ab der Benutzerrolle "Supervisor" in der Kategorie "Usersettings" freischalten.

**Comment by Patrick-Werner-WEBTH** [comment]
- Nutzerrollen umbenannt.
- Permissionrolle "Settings" in "User" umbenannt.
- Neu erstellte Nutzers werden nun zum "Worker".
- Zugriffsrechte angepasst.
